name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
      - '.github/workflows/deploy.yml'

# Allow this job to clone the repo and commit to the gh-pages branch
permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set up Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'client/package-lock.json'

      - name: Install and Build 🔧
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_PUBLIC_URL: ${{ vars.VITE_PUBLIC_URL }}
        run: |
          cd client
          npm install
          npm run build
          # Workaround for SPA routing on GitHub Pages
          cp dist/index.html dist/404.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: client/dist
          branch: gh-pages
